# Bayesian reasoning in the Twilight Zone

In the special case where we have two competing hypothesis which negate each other e.g.

H : Mystic Seer truely can predict the future

<SPAN STYLE="text-decoration:overline">H</SPAN> : The Mystic Seer just got lucky


P(D|H) is the probability of getting n correct answers in a row is 1

P(D|<SPAN STYLE="text-decoration:overline">H</SPAN>) is the probability of getting n correct answers in a row is 0.5<sup>n</sup>

### Measuring the Bayes Factor

BF = <sup>P(D<sub>n</sub>|H)</sup>/<sub>P(D<sub>n</sub>|<SPAN STYLE="text-decoration:overline">H</SPAN>)</sub> = <sup>1</sup>/<sub>0.5<sup>n</sup></sub>

### Prior Odds

prior odds = O(H) = <sup>P(H)</sup>/<sub>P(<SPAN STYLE="text-decoration:overline">H</SPAN>)</sub>

---

# Exercise 1

<b>
    You flip a coin to choose who selects the movie to watch when you meet your friend every Friday.
    Your friend always picks heads and has been right for 10 weeks.
    You develop a hypothesis that the coin has heads for both sides.
    Setup a Bayes factor for the hypothesis.

</b>

We have a change in the prior odds. Now:

BF = 1 / 0.5<sup>10</sup>

In [1]:
1 / 0.5**10

1024.0

So the BF says it is 1024 times likely that the coin is a trick coin

# Exercise 2

<b>
    Imagine three cases, your friend is:
    <ol type="1">
        <li>a prankster</li>
        <li>honest most of the time but can be sneaky</li>
        <li>is trustworthy</li>
    </ol>
    In each case, estimate some prior odds ratios for your hypothesis and compute the posterior odds
</b>

Using the Bayes Factor from the previous question i.e. 1024.0

We estimate the Prior odds for each case and calculate the posterior odds

<ol type="1">
    <li>Prankster: O(H<sub>1</sub>) = 10 then Posterior Odds = 10 * 1024 = 10,240</li>
    <li>Honest most of the time: O(H<sub>1</sub>) = 1/4 then Posterior Odds = 1/4 * 1024 = 240</li>
    <li>Trustworthy: O(H<sub>1</sub>) = 1/10,000 then Posterior Odds = 1/10,000 * 1024 &thickapprox; 1/10</li>
</ol>

# Exercise 3

<b>
    Suppose you trust this friend deeply. Make the prior odds of them cheating 1/10,000. How many times would the coin have to land on heads before you feel unsure about their innocence-say, a posterior odds of 1?
</b>

In [10]:
prior_odds = 1/10_000

while True:
    bayes_factor = (1/(0.5**i))
    posterior_odds = prior_odds * bayes_factor
    if posterior_odds > 1.0:
        print(f'feel suspicious after {i} coin flips land heads')
        break



feel suspicious after 14 coin flips land heads


# Exercise 4

<b>
    Another friend of yours also hange our with this same friend and, after only four weeks of the coin landing on heads, feels certain you're both being cheated. This confidence implies a posterior odds of about 100. What value would you assign to this friend's prior belief that the first friend is a cheater?
</b>


P(D | H<sub>2</sub>) = 0.5 <sup>4</sup> = 1/16

BF = 1 / (1/16) = 16

100 = O(H) * 16

O(H) = 100 / 16 = 6<sup>1</sup>/<sub>4</sub>